version: '3.9'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - 5432:5432
  application:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 5173:5173
